package test_agent.models;

/**
 * Represents a generated test with its code and any required imports.
 * This class is used to store and manage test code generated by the AI.
 */
public class GeneratedTest {
    private String testCode;
    private String newImportsCode;

    /**
     * Constructs a new GeneratedTest with the specified test code and imports.
     *
     * @param testCode The code for the test function/method
     * @param newImportsCode Any additional import statements needed for the test
     */
    public GeneratedTest(String testCode, String newImportsCode) {
        this.testCode = testCode;
        this.newImportsCode = newImportsCode;
    }


    public String getTestCode() {
        return testCode;
    }



    public String getNewImportsCode() {
        return newImportsCode;
    }


    /**
     * Creates a GeneratedTest from a dictionary/map representation.
     *
     * @param testDict A map containing test_code and new_imports_code keys
     * @return A new GeneratedTest instance
     */
    public static GeneratedTest fromMap(java.util.Map<String, Object> testDict) {
        String testCode = (String) testDict.getOrDefault("test_code", "");
        String newImportsCode = (String) testDict.getOrDefault("new_imports_code", "");

        // Clean up the imports if necessary
        if (newImportsCode != null && newImportsCode.startsWith("\"") && newImportsCode.endsWith("\"")) {
            newImportsCode = newImportsCode.substring(1, newImportsCode.length() - 1);
        }

        // Check if additional_imports only contains '""':
        if (newImportsCode != null && newImportsCode.equals("\"\"")) {
            newImportsCode = "";
        }

        return new GeneratedTest(testCode.trim(), newImportsCode.trim());
    }

    /**
     * Converts this GeneratedTest to a map representation.
     *
     * @return A map containing the test code and import code
     */
    public java.util.Map<String, String> toMap() {
        java.util.Map<String, String> map = new java.util.HashMap<>();
        map.put("test_code", testCode);
        map.put("new_imports_code", newImportsCode);
        return map;
    }

    @Override
    public String toString() {
        return "GeneratedTest{" +
                "testCode='" + testCode + '\'' +
                ", newImportsCode='" + newImportsCode + '\'' +
                '}';
    }
}